version: "3.8"
services: 
    mongo:
        image : mongo
        command: mongod
        volumes: 
            - ./data:/data/db
            - "./mongo-entrypoint/:/docker-entrypoint-initdb.d/"
        container_name: holomon-database
        env_file:
            - .env
        ports:
            - 27017:27017
        restart: unless-stopped