version: "3.8"
services: 
    mongo:
        image : mongo
        command: --serviceExecutor adaptive
        volumes: 
            - ./data:/data/db
        container_name: holomon-database
        environment: 
            - PUID=1000
            - PGID=1000
        ports:
            - 27017:27017
        restart: unless-stopped